"""Reset the case2 lab back to its clean pre-attack state.

Removes every artifact produced by run_attack.py / build_report.py, then
regenerates the 200 benign victim files + manifest.

  python reset_lab.py          # reset + repopulate victim folder
  python reset_lab.py --no-refill   # reset only, leave victim folder empty

Usage (equivalent, for reference):
  del /Q C:\\case2_lab\\evidence\\baseline\\baseline_files.json C:\\case2_lab\\evidence\\baseline\\baseline_system.json
  del /Q C:\\case2_lab\\evidence\\post\\post_attack_files.json
  del /Q C:\\case2_lab\\logs\\simulation_*.json C:\\case2_lab\\logs\\ransomware_alert_*.json
  for /D %d in (C:\\case2_lab\\runs\\*) do rmdir /S /Q "%d"
  del /S /Q C:\\Tests_reports\\*.locked
  del /Q C:\\Tests_reports\\README_RANSOMWARE_SIMULATION.txt
  del /Q "%USERPROFILE%\\Desktop\\README_RANSOMWARE_SIMULATION.txt"
  python simulator\\generate_test_data.py
"""
import argparse
import os
import shutil
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(PROJECT_ROOT))

from lab_paths import CONFIG, LAB_ROOT, LOG_DIR  # noqa: E402

RUNS_DIR = PROJECT_ROOT / "runs"
EVIDENCE = PROJECT_ROOT / "evidence"
REPORTS = PROJECT_ROOT / "reports"


def remove(path: Path, label: str) -> None:
    if not path.exists():
        return
    if path.is_dir():
        shutil.rmtree(path, ignore_errors=True)
        print(f"[removed] dir  {label}")
    else:
        path.unlink()
        print(f"[removed] file {label}")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--no-refill", action="store_true", help="do not regenerate victim files")
    args = ap.parse_args()

    note_name = CONFIG["ransom_note"]
    desktop = Path(os.environ.get("USERPROFILE", str(Path.home()))) / "Desktop" / note_name

    print("=" * 60)
    print("CASE2 LAB RESET")
    print("=" * 60)

    # 1. Evidence
    remove(EVIDENCE / "baseline" / "baseline_files.json", "baseline_files.json")
    remove(EVIDENCE / "baseline" / "baseline_system.json", "baseline_system.json")
    remove(EVIDENCE / "post" / "post_attack_files.json", "post_attack_files.json")

    # 2. Logs (keep fp_test_*.json as tuning evidence; drop run-specific ones)
    for pattern in ("simulation_*.json", "ransomware_alert_*.json"):
        for f in LOG_DIR.glob(pattern):
            remove(f, f.name)

    # 3. Run bundles
    if RUNS_DIR.exists():
        for d in RUNS_DIR.iterdir():
            if d.is_dir():
                remove(d, f"runs/{d.name}")

    # 4. Reports (regenerated by build_report.py)
    for pattern in ("analysis_summary.json", "report_*.html", "0*.png"):
        for f in REPORTS.glob(pattern):
            remove(f, f"reports/{f.name}")

    # 5. Victim folder
    for locked in LAB_ROOT.rglob("*.locked"):
        remove(locked, str(locked.relative_to(LAB_ROOT)))
    remove(LAB_ROOT / note_name, str(LAB_ROOT / note_name))

    # 6. Desktop note
    remove(desktop, str(desktop))

    print("-" * 60)
    if args.no_refill:
        print("Reset complete. Victim files NOT regenerated (--no-refill).")
    else:
        sys.path.insert(0, str(PROJECT_ROOT / "simulator"))
        import generate_test_data
        print("Regenerating victim files...")
        generate_test_data.main()
        print("Reset complete — lab is back to pre-attack state.")
    print("=" * 60)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
